Django_User_Management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ESGmanager.urls')),
    path('accounts/', include('accounts.urls')),
]

ESGmanager/urls.py
from django.urls import path, re_path
from . import views

app_name = 'ESGmanager'

urlpatterns = [
    path('', views.login, name='landing_page'),
    path('activity/<slug:username>/', views.activity_list, name='activity_list'),
    path('totalpoints/<slug:username>/', views.total_points, name='total_points'),
    path('metamask/<slug:username>', views.metamask, name='metamask'),
]

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

ESGmanager/models.py
from django.db import models
from django.conf import settings


class ESGData(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    activity = models.CharField(max_length=70)
    poi = models.IntegerField()

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    wallet_addr = models.CharField(max_length=42)

accounts/forms.py
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['wallet_addr']

ESGmanager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from .models import ESGData


login = LoginView.as_view(template_name='accounts/index.html')


@login_required
def activity_list(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)
    if page_user == 'admin':
        activity_list = ESGData.objects.all()
    else:
        activity_list = ESGData.objects.all().filter(user=page_user)
    return render(request, 'activities.html', {
        'page_user': page_user,
        'activity_list': activity_list,
    })


@login_required
def total_points(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)
    total_points = ESGData.objects.all().filter(user=page_user).aggregate(Sum('poi'))
    return render(request, 'integrationPoint.html', {
        'page_user': page_user,
        'total_points': total_points,
    })


@login_required
def metamask(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)
    return render(request, 'connectWallet.html', {
        'page_user': page_user,
    })

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, logout_then_login
from accounts.forms import UserForm
from accounts.models import User


login = LoginView.as_view(template_name='accounts/index.html')


def logout(request):
    return logout_then_login(request)


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


@login_required
def profile_edit(request):
    try:
        profile = request.user.username
    except User.DoesNotExist:
        profile = None

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('profile')
    else:
        form = UserForm(instance=profile)
    return render(request, 'accounts/profile_form.html', {
        'form': form,
    })

ESGmanager/templates/activities.html
<!-- activities -->

<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ESG</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>

<div class="header">
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">ESG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ESGmanager:activity_list' page_user.username %}">활동내역</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'ESGmanager:total_points' page_user.username %}">통합포인트</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url 'ESGmanager:metamask' page_user.username %}">지갑연동</a>
                        </li>
                    </ul>
                </div>
                <div class="user">
                    <ul class="navbar-nav">
                        <li class="nav-item ms-2">{{ page_user.username }}</li>
                    </ul>
                </div>
            </div>

        </nav>
    </div>
</div>

<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center">
        <h1 class="my-5 text-center">활동내역</h1>

        <table class="table table-hover">
            <thead>
                <tr>
                    {% if page_user.username == 'admin' %}
                    <th scope="col">User</th>
                    {% endif %}
                    <th scope="col">Date</th>
                    <th scope="col">Activity</th>
                    <th scope="col">Poi</th>
                </tr>
            </thead>
            {% for activity in activity_list %}
            <tbody class="table-group-divider">
                <tr>
                    {% if page_user.username == 'admin' %}
                        <td>{{ activity.user }}</td>
                    {% endif %}
                        <td>{{ activity.datetime }}</td>
                        <td>{{ activity.activity }}</td>
                        <td>{{ activity.poi }}</td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>
</html>

ESGmanager/templates/connectWallet.html
<!-- connect wallet -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ESG</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>

<div class="header">
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">ESG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ESGmanager:activity_list' page_user.username %}">활동내역</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'ESGmanager:total_points' page_user.username %}">통합포인트</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url 'ESGmanager:metamask' page_user.username %}">지갑연동</a>
                        </li>
                    </ul>
                </div>
                <div class="user">
                    <ul class="navbar-nav">
                        <li class="nav-item ms-2">{{ page_user.username }}</li>
                    </ul>
                </div>
            </div>

        </nav>
    </div>
</div>

<section>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <img src="{% static 'images/MetaMask_Fox.png' %}" alt="metamask_fox" class="card-img-top w-50"/>

                        <div>
                            <button id="connect-button" class="btn btn-lg btn-secondary">Connect Metamask</button>
                        </div>

                        <div class="connected-container m-3">
                            <p class="isConnected"></p>
                            <p class="address"></p>
                            <p class="balance"></p>
                        </div>

                        <div>
                            <button id="send-button" class="btn btn-lg btn-secondary" hidden>Send ETH</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'js/requestEth.js' %}"></script>

</body>
</html>

ESGmanager/templates/integrationPoint.html
<!-- integration point -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ESG</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <style>
        #chartdiv {
            width: 100%;
            height: 500px;
        }
    </style>

</head>
<body>
<div class="header">
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">ESG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ESGmanager:activity_list' page_user.username %}">활동내역</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'ESGmanager:total_points' page_user.username %}">통합포인트</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url 'ESGmanager:metamask' page_user.username %}">지갑연동</a>
                        </li>
                    </ul>
                </div>
                <div class="user">
                    <ul class="navbar-nav">
                        <li class="nav-item ms-2">{{ page_user.username }}</li>
                    </ul>
                </div>
            </div>

        </nav>
    </div>
</div>

<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center">

        <h1 class="my-5 text-center">통합 포인트</h1>

        <div class="description m-auto text-center">
            <h2 class="point">{{ total_points.poi__sum }}</h2>
            <p>포인트를 모으셨습니다.</p>
            <button type="button" id="transformPoint" class="btn btn-secondary btn-lg" onclick="confirm('개발 진행중 입니다.')">포인트 전환 신청</button>
        </div>

        <div id="chartdiv" class="my-5"></div>

    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

<!-- Resources -->
<script src="https://cdn.amcharts.com/lib/5/index.js"></script>
<script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
<script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
<!-- Chart code -->
<script type="text/javascript" src="{% static 'js/drawPointChart.js' %}"></script>
</body>
</html>

accounts/templates/accounts/index.html
<!-- login -->

<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ESG</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>

<section class="vh-100" style="background-color: #508bfc;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <h1 class="mb-5">Login</h1>
                        <form action="" method="post">
                            {% csrf_token %}

                        <div class="form-outline mb-4 text-start">
                            <label class="form-label" for="typeEmailX-2">Email</label>
{#                            <input type="email" id="typeEmailX-2" class="form-control form-control-lg" value="" />#}
                            <div class="form-control form-control-lg">{{ form.username }}</div>
                        </div>

                        <div class="form-outline mb-4 text-start">
                            <label class="form-label" for="typePasswordX-2">Password</label>
                            <div class="form-control form-control-lg">{{ form.password }}</div>
{#                            <input type="password" id="typePasswordX-2" class="form-control form-control-lg" value="" />#}
                        </div>

                        <div class="d-grid gap-2">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
                        </div>

                        </form>
                        <hr class="my-5">

                        <div class="d-grid gap-2">
                            <button class="btn btn-lg btn-block btn-primary mb-2" style="background-color: #3b5998;"
                                    type="submit"><i class="bi bi-facebook"></i> 페이스북으로 로그인하기
                            </button>
                            <button class="btn btn-lg btn-block btn-primary" style="background-color: #dd4b39;"
                                    type="submit"><i class="bi bi-google"></i> 구글로 로그인하기
                            </button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/profile.html
<h2>User: {{ user }}</h2>

{% if user.profile %}
    <ul>
        <li>{{ user.profile.wallet_addr }}</li>
    </ul>
{% endif %}

<a href="{% url "profile_edit" %}">프로필 수정</a>

accounts/templates/accounts/profile_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="수정하기" />
</form>